# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_auto_20160630_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='enforce_issue_location_in_area',
            field=models.BooleanField(default=False, help_text='Enforce issues to be in this sites area'),
        ),
    ]
