# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 17:14
from __future__ import unicode_literals

from django.db import migrations


def create_site_configs(apps, schema_editor):
    from ..signals import create_site_config
    Site = apps.get_model("sites", "Site")

    sites = Site.objects.filter(siteconfig__isnull=True)
    for s in sites:
        create_site_config(instance=s)

class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_siteconfig_enforce_issue_location_in_area'),
        ('sites', '0002_alter_domain_unique')
    ]

    operations = [
        migrations.RunPython(create_site_configs),
    ]
