# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20160503_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'issue', 'verbose_name_plural': 'issues'},
        ),
        migrations.AlterModelOptions(
            name='issuecomment',
            options={'get_latest_by': 'created', 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
    ]
