# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issuecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuecomment',
            options={'ordering': ['-created'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
