# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 21:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20160411_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='location'),
        ),
    ]
