# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 21:08
from __future__ import unicode_literals

from django.db import migrations

def port_locations(apps, schema_editor):
    Issue = apps.get_model('issues', 'Issue')
    for i in Issue.objects.filter(location__isnull=False):
        i.point = i.location.location
        i.save()

    # raise NotImplementedError


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_point'),
    ]

    operations = [
        migrations.RunPython(port_locations)
    ]
