# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 14:01
from __future__ import unicode_literals

from django.db import migrations, models


def set_status_choice(apps, schema_editor):

        Issue = apps.get_model('issues', 'Issue')
        IssueStatus = apps.get_model('issues', 'IssueStatus')

        for issue in Issue.objects.all():
            issue_status = IssueStatus.objects.filter(issue=issue).latest('created')
            issue.current_status = issue_status.status
            issue.save()



class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20160511_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='current_status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], db_index=True, default='open', max_length=10),
        ),
        migrations.RunPython(set_status_choice)
    ]
