# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_move_locations_to_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='location',
        ),
    ]
