# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_issuestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-created',), 'verbose_name': 'issue', 'verbose_name_plural': 'issues'},
        ),
    ]
