# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_auto_20160421_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.IssueType'),
        ),
    ]
