# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_issue_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description_format',
            field=models.CharField(blank=True, choices=[('', 'Just text'), ('markdown', 'Markdown'), ('html', 'HTML')], default='', max_length=20),
        ),
    ]
