# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 09:53
from __future__ import unicode_literals

from django.db import migrations


def migrate_issue_types(apps, schema_editor):
    Issue = apps.get_model('issues', 'Issue')
    issues = Issue.objects.all().select_related('issue_type')
    for issue in issues:
        issue.issue_types.add(issue.issue_type)
        assert(issue.issue_type_id == issue.issue_types.all()[0].pk)

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20161009_0953'),
    ]

    operations = [
        migrations.RunPython(migrate_issue_types)
    ]
