# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_remove_toucaninvitation_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toucaninvitation',
            name='role',
            field=models.IntegerField(choices=[(0, 'member'), (5, 'admin')], default=0),
        ),
    ]
