# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 08:52
from __future__ import unicode_literals

from django.db import migrations
import toucan.notifications


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_user_mention_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_mention_notification',
            field=toucan.notifications.fields.NotificationTypeField(blank=True, choices=[('', 'No notification'), ('sms', 'Text Message (SMS)'), ('email', 'Email')], default='', max_length=20, verbose_name='Notification when mentioned'),
        ),
    ]
