# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 14:03
from __future__ import unicode_literals

from django.db import migrations
import toucan.notifications

class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20160525_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_mention_notification',
            field=toucan.notifications.fields.NotificationTypeField(blank=True, choices=[('', 'No notification'), ('sms', 'Text Message (SMS)'), ('email', 'Email')], default='', max_length=20, verbose_name='Notification when your organisation is mentioned'),
        ),
    ]
