# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='toucan.issues.Issue'),
        ),
        migrations.AlterField(
            model_name='issuestatus',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='toucan.issues.Issue'),
        ),
    ]
