# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 07:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20160427_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuestatus',
            options={'get_latest_by': 'created', 'verbose_name': 'issue status', 'verbose_name_plural': 'issue statuses'},
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='draft_struct',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='issue',
            name='organisation',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='toucan.organisations.Organisation', verbose_name='organisation'),
        ),
    ]
