# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='current_status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], db_index=True, default='open', max_length=10, verbose_name='issue status'),
        ),
    ]
