# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_issue_description_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_types',
            field=models.ManyToManyField(to='toucan.issues.IssueType', verbose_name='issue type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deprecated_issue_type', to='toucan.issues.IssueType', verbose_name='issue types'),
        ),
    ]
