# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_remove_issue_issue_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='site',
        ),
    ]
