# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_issuetype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='current_status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'resolved')], db_index=True, default='open', max_length=10, verbose_name='issue status'),
        ),
        migrations.AlterField(
            model_name='issuestatus',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'resolved')], db_index=True, max_length=10),
        ),
    ]
