# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_auto_20161225_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuetype',
            name='svg_icon',
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
