# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_auto_20161225_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='main_issue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issues.IssueType', verbose_name='issue type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_types',
            field=models.ManyToManyField(blank=True, related_name='all_issues', to='issues.IssueType', verbose_name='issue type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='issue title'),
        ),
    ]
