# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170821190322 on 2017-08-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0017_auto_20170806_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='pick_up_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='current_status',
            field=models.CharField(choices=[('open', 'open'), ('in_progress', 'in progress'), ('closed', 'resolved')], db_index=True, default='open', max_length=10, verbose_name='issue status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_types',
            field=models.ManyToManyField(to='issues.IssueType', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='issuestatus',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in_progress', 'in progress'), ('closed', 'resolved')], db_index=True, max_length=10),
        ),
    ]
