# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 09:45
from __future__ import unicode_literals

from django.db import migrations


def singleIssueType(apps, schema_editor):
    Issue = apps.get_model('issues', 'Issue')

    for issue in Issue.objects.all():
        if not issue.main_issue_type:
            try:
                it = issue.issue_types.all()[0]
            except IndexError:
                continue

            issue.main_issue_type = it
            issue.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0017_auto_20170228_0936'),
    ]

    operations = [
        migrations.RunPython(singleIssueType)
    ]
