# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170822103810 on 2017-08-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0019_auto_20170822_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='current_status',
            field=models.CharField(choices=[('open', 'open'), ('in_progress', 'in progress'), ('closed', 'resolved')], db_index=True, default='open', max_length=11, verbose_name='issue status'),
        ),
    ]
