# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170827125642 on 2017-08-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_auto_20170827_1255'),
        ('issues', '0020_auto_20170822_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Location', verbose_name='location'),
        ),
    ]
