# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170916090346 on 2017-09-16 09:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0021_issue_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='location'),
        ),
    ]
