# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170926133457 on 2017-09-26 17:01
from __future__ import unicode_literals

from django.db import migrations
from toucan.issues.utils import draft_struct_to_comment

def renderComments(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    IssueComment = apps.get_model('issues', 'IssueComment')
    comments = IssueComment.objects.all()

    for c in comments:
        if c.draft_struct:
            comment_text = draft_struct_to_comment(c.draft_struct)
            if c.comment != comment_text:
                c.comment = comment_text
                c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0022_auto_20170916_0958'),
    ]

    operations = [
        migrations.RunPython(renderComments)
    ]
