# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170926173153 on 2017-09-26 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0023_auto_20170926_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuecomment',
            name='draft_struct',
        ),
    ]
