# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170825220037 on 2017-08-27 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_auto_20170825_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='can_assign_issue',
            field=models.BooleanField(default=True, verbose_name='Issue assignable'),
        ),
        migrations.AddField(
            model_name='location',
            name='display_on_map',
            field=models.BooleanField(default=True, verbose_name='Display on organisation map'),
        ),
    ]
