# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170916090346 on 2017-09-16 09:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_auto_20170827_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='location_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='location description'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='telephone number'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location'),
        ),
    ]
