# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_notificationsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationsettings',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-created',)},
        ),
    ]
