# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_org_mention_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='point_radius',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='radius in kilometers'),
        ),
    ]
