# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
