# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_membership_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('name',), 'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
    ]
