# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20160420_1038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('org', 'user')]),
        ),
    ]
