# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20160421_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='short_name',
            field=models.SlugField(verbose_name='short name'),
        ),
    ]
