# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_auto_20161220_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.IntegerField(choices=[(0, 'member'), (5, 'admin')], default=0),
        ),
    ]
