# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import organisations.models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_auto_20160426_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='short_name',
            field=models.SlugField(validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), organisations.models.validate_organisation_slug], verbose_name='short name'),
        ),
    ]
